# Automate generation of release PRs using Conventional Commits
# See https://github.com/googleapis/release-please

on:
  push:
    branches:
      - master

name: release-please
jobs:
  release-please:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
